Ace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^auth/', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    url(r'^$', views.index, name='index'),
    

]

users/urls.py
from django.conf.urls import url
from .views import register, user_login, user_logout, user_info

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^profile/$', user_info, name='profile')
]

base/models.py
from datetime import datetime
from django.db import models
from stdimage import StdImageField

departments=(
        ('Physics','Physics'),
        ('Chemistry','Chemistry'),
        ('Mathematics','Mathematics'),
        ('Biology','Biology'),
        ('Computer Sc.','Computer Sc.'),
        ('History/Geography','History/Geography'),
        ('Second Language', 'Second Language'),
        ('Others','Others'),
    )

# Create your models here.

class Course(models.Model):
    types=(('cogs','Gear Icon'),('stethoscope','Medic Icon'),('graduation-cap','Foundation Course'))
    Type=models.CharField(max_length=15,choices=types,default='cogs')
    name=models.CharField(max_length=100)
    details=models.CharField(max_length=1200)
    def __str__(self):
        return("Course name is: {} ".format(str(self.name)))


class Teachers(models.Model):
    depts=departments
    name=models.CharField(max_length=50)
    dept=models.CharField(max_length=20,choices=depts,default='Mathematics')
    details=models.CharField(max_length=1000)
    image= models.URLField(max_length=200, help_text="Please Enter the URL here(GDrive/Amazon Drive/Facebook)")

    class Meta:
        verbose_name_plural="Faculty"
    
    def __str__(self):
        return(str(self.name))


class Gallery(models.Model):
    subjects=departments
    image= models.URLField(max_length=200, help_text="Please Enter the URL to photo here (GDrive/Amazon Drive/Facebook)")
    subject=models.CharField(max_length=20,choices=subjects,default='Mathematics')
    descriptions=models.CharField(max_length=500)
    date=models.DateTimeField(default=datetime.now, blank=True)

    class Meta:
        verbose_name_plural="Gallery"

    def __str__(self):
        return("Image of {} class".format(str(self.subject)))

class About(models.Model):
    title=models.CharField(max_length=300)
    detail=models.CharField(max_length=1200)

    class Meta:
        verbose_name_plural="About"

    def __str__(self):
        return("About: {}".format(str(self.title)))

class Achievement(models.Model):
    title=models.CharField(max_length=300)
    no=models.IntegerField(default=0)

    def __str__(self):
        return("Achievement "+str(self.title))

class Feedback(models.Model):

    your_name = models.CharField(max_length=120)
    email = models.EmailField()
    details = models.TextField()
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural="Feedback"

    def __str__(self):
        return self.your_name

base/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):

    your_name = forms.CharField(widget=forms.TextInput(
        attrs={'size': '48', 'class': 'form-control', 'placeholder': 'Your Name'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'size': '48', 'class': 'form-control', 'placeholder': 'Email Address'}))
    details = forms.CharField(widget=forms.Textarea(
        attrs={'size': '48', 'class': 'form-control', 'placeholder': 'Please leave your Message'}))

    class Meta:
        model=Feedback
        fields=('your_name','email','details')

base/views.py
from django.shortcuts import render
from .models import Course,Teachers,Gallery,About,Achievement
from .forms import FeedbackForm
# Create your views here.
def index(req):
    
    contents={}

    # Course setup
    course=Course.objects.all()
    contents['course']=course

    # Gallery
    gallery=Gallery.objects.all()
    contents['gallery']=gallery

    #About
    about=About.objects.all()
    contents['about']=about

    # Teachers
    teachers=Teachers.objects.all()
    contents['teachers']=teachers
    
    #Achievements
    achievements=Achievement.objects.all()
    contents['achievements']=achievements

    #Feedback Form
    if(req.method == 'POST'):
        form = FeedbackForm(req.POST)
        contents['form'] = form

        if form.is_valid():
            form.save()
            print("posted")
            return render(req, 'base/base.html', context=contents)

    else:
        form = FeedbackForm()
        contents['form'] = form


    return(render(
        req, 'base/base.html', context=contents
    ))

templates/base/base.html
{% extends "base/structure.html" %}

{% block content %}
{% load staticfiles %}


    <!-- Header of The Page -->
    <header class="text-center" name="home">
      <div class="header-box">
          <img src="{% static "base/img/header.jpg" %}" alt="HeaderImage" id='headerimg' style="width:100%;">
          <div class="intro-text">
            <h1>Welcome to <strong>ACE Foundation Academy</strong></h1>
            <p>We nurture minds not machines..</p>
            <a href="#services-section" class="btn btn-default btn-lg page-scroll">LEARN MORE</a>
          </div>
      </div>
    </header>

      <!-- Navigation  ==========================================-->
      <nav id="menu" class="navbar navbar-default navbar-fixed-top chastate">
        <div class="container"> 
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="">
              <strong><img src="{% static "base/img/ace.png" %}" width="40" alt=""> Ace Foundation Academy </strong></a> </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#home" class="page-scroll">Home</a></li>
              <li><a href="#services-section" class="page-scroll">Courses</a></li>
              <li><a href="#gallery" class="page-scroll">Gallery</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'notes' %}" class="page-scroll">Notes</a></li>
              {% endif %}
              <li><a href="#about-section" class="page-scroll">About</a></li>
              <li><a href="#team-section" class="page-scroll">Teachers</a></li>
              <li><a href="#contact-section" class="page-scroll">Contact</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'users:logout' %}" class="page-scroll authen">Logout</a></li>
              <li><a href="{% url 'users:profile' %}" class="page-scroll authen">Profile</a></li>
              {% else %}
              <li><a href="{% url 'users:login' %}" class="page-scroll authen">Login</a></li>
              <li><a href="{% url 'users:register' %}" class="page-scroll authen">Register</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
  </nav>
    

  <!-- COURSES Section -->
  <div id="services-section" class="text-center">
    <div class="container">
      <div class="section-title center">
        <h2>Our Courses</h2>
        <hr>
        <div class="clearfix"></div>
        <p>Here are the list of subjects that we offer.</p>
      </div>
      <div class="space"></div>
      <div class="row">

        {% if course %}
          <!--stethoscope -->
          <!-- cogs -->
          <!-- graduation-cap -->
          {% for c in course%}
          <div class="col-md-3 col-sm-6 service"> <i class="fa fa-{{c.Type}}" aria-hidden="true" style="color:firebrick"></i>
            <h4>{{c.name}}</h4>
            <p>{{c.details}}</p>
          </div>
          {% endfor %}
        {% else %}
        <p>No Course Added Yet</p>
        {% endif %}

      </div>
    </div>
  </div>



<!-- Gallery Section -->
<div id="gallery">
    <div class="container">
       <!-- Container -->
      <div class="section-title text-center center">
        <h2>Our Gallery</h2>
        <hr>
        <div class="clearfix"></div>
        <p>Here are some snapshots of growing mind</p>
      </div>

      <div class="categories">
        <ul class="cat">
          <li>
            <ol class="type">
              <li><a href="#" data-filter="*" class="active">All</a></li>
              <li><a href="#" data-filter=".Biology">Biology</a></li>
              <li><a href="#" data-filter=".Mathematics">Maths</a></li>
              <li><a href="#" data-filter=".Physics">Physics</a></li>
              <li><a href="#" data-filter=".Chemistry">Chemistry</a></li>
              <li><a href="#" data-filter=".Computer">Computer</a></li>
              <li><a href="#" data-filter=".Others">Others</a></li>
            </ol>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="row">
        <div class="portfolio-items">

          <!-- Subject should be mentioned. -->
        {% if gallery %}
        {% for img in gallery %}
        <div class="col-sm-6 col-md-3 col-lg-3 {{img.subject}}">
          <div class="portfolio-item">
            <div class="hover-bg"> <a href="{{img.image}}" rel="prettyPhoto">
              <div class="hover-text">
                <h4>{{img.subject}}</h4>
                <small>{{img.descriptions}}</small>
                <div class="clearfix"></div>
              </div>
              <img src="{{img.image}}" class="img-responsive" alt="{{img.subject}}"> </a> </div>
          </div>
        </div>
        {% endfor %}

        {% else %}
        <div class="jumbotron">
          <div class="container">
            <p>NO IMAGE FOUND IN GALLERY</p>
          </div>
        </div>
        {% endif %}
  
        </div>
      </div>
    </div>
  </div>


  <!-- About Section -->

<div id="about-section">
  <div class="container">
    <div class="section-title text-center center">
      <h2>About Us</h2>
      <hr>
      <div class="clearfix"></div>
      <p>Come, get to know about us</p>
    </div>
    <div class="row">
      <div class="col-md-6"> <img src="{% static "base/img/about.jpg" %}" class="img-responsive"> </div>
      <div class="col-md-6">
        <div class="about-text">
          {% if about %}
          {% for abt in about %}

          <h4>{{abt.title}}</h4>
          <p>{{abt.detail}}</p>

          {% endfor %}
          {% else %}
          <h4>COME VISIT US TO KNOW MORE</h4>
          <p>Hurry</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>




<!-- Team Section -->
<div id="team-section" class="text-center">
    <div class="container">
      <div class="section-title center">
        <h2>Meet Our Guides</h2>
        <hr>
        <p>A tour can't take place without a guide, meet our torch-bearers</p>
      </div>
      <div id="row">
        {% if teachers %}

        {% for teacher in teachers %}
        <div class="col-md-3 col-sm-6 team">
          <div class="thumbnail"> <a href="{{teacher.image}}" rel="prettyPhoto"><img src="{{teacher.image}}" alt="Photo" class="img-circle team-img"></a>
            <div class="caption">
              <h3>{{teacher.name}}</h3>
              <p>Department of {{teacher.dept}}</p>
              <p>{{teacher.details}}</p>
            </div>
          </div>
        </div>
        {% endfor %}

        {% else %}
        <h2>Plese Add the teachers</h2>
        {% endif %}
      </div>
    </div>
  </div>




<!-- achievements -->
{% if achievements %}
<div id="achievements" class="section dark-bg">
  <div class="container">
    <div class="row">
      {% for achievement in achievements %}
      <div class="col-md-3 col-sm-3">
        <div class="achievement-box"> <span class="count">{{achievement.no}}</span>
          <h4>{{achievement.title}}</h4>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}



<!-- Contact Section -->
<div id="contact-section" class="text-center">
    <div class="container">
      <div class="section-title center">
        <h2>Contact Us</h2>
        <hr>
        <p>Feel free to contact us in our given address</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <div class="col-md-4"> <i class="fa fa-map-marker"></i>
          <p>Habra Staff Quater<br>
            India,WB,24 parganas North- 743263</p>
        </div>
        <div class="col-md-4"> <i class="fa fa-envelope-o"></i>
          <p>acefoundation@gmail.com</p>
        </div>
        <div class="col-md-4"> <i class="fa fa-phone"></i>
          <p>8001183508 / 8914136530</p>
        </div>
        
        <div class="clearfix"></div>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h3>Leave us a message</h3>

        <form name="sentMessage" id="contactForm" action="{% url 'index' %}" method="POST">
          {% csrf_token %}

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                {{ form.your_name }}
                <p class="help-block text-danger"></p>
              </div>
            </div>

            <div class="col-md-6">
              <div class="form-group">
                {{ form.email }}
                <p class="help-block text-danger"></p>
              </div>
            </div>

          </div>

          <div class="form-group">
            {{ form.details }}
            <p class="help-block text-danger"></p>
          </div>
          <div id="success"></div>
          <input type="submit" class="btn btn-default" value="Submit">
        </form>

      </div>
    </div>
  </div>
  </div>

{% endblock %}

templates/base/structure.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ace Foundation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icons -->
    <link rel="shortcut icon" href="{% static "base/img/ace.png" %}" type="image/png">
    <link rel="apple-touch-icon" href="{% static "base/img/apple-touch-icon.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "base/img/apple-touch-icon-72x72.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "base/img/apple-touch-icon-114x114.png" %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/bootstrap.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/prettyPhoto.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/style.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "base/fonts/font-awesome/css/font-awesome.css" %}">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
    <!-- js -->
    <script type="text/javascript" src="{% static "/base/js/modernizr.custom.js" %"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
    <script type="text/javascript" src="{% static "/base/js/jquery.1.11.1.js" %}"></script> 
    <script>
      $(window).load(function() {
        setTimeout(()=>{
          $(".se-pre-con").fadeOut('medium');
        },300);
      });</script>
</head>
<body>


    <!-- All the other stuffs goes in here -->

    {% block content %}

    {% endblock %}


    <!-- Rest of the thing goes on -->
    <div id="social-section">
        <div class="container">
          <div class="social">
            <ul>
              <li><a href="https://www.facebook.com/Ace Foundation"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    <!-- Footer Part Begins -->
    <div id="footer">
        <div class="container">
          <div class="fnav">
            <p>Copyright &copy; Ace Foundation. Designed <a href="http://www.github.com/xritzx" rel="nofollow">by</a></p>
          </div>
        </div>
    </div>

<!-- All of the needed javascript Files -->
<script type="text/javascript" src="{% static "base/js/bootstrap.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/SmoothScroll.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.counterup.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/waypoints.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.prettyPhoto.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.isotope.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jqBootstrapValidation.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/main.js" %}"></script>

</body>
<style>
  .no-js #loader { display: none;  }
.js #loader { display: block; position: absolute; left: 100px; top: 0; }
.se-pre-con {
	position: fixed;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	z-index: 9999;
	background: url("{% static "/loader/loader.svg" %}") center no-repeat #fff;
}
</style>
<div class="se-pre-con"></div>

</html>

templates/base/structure_nav.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ace Foundation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icons -->
    <link rel="shortcut icon" href="{% static "base/img/ace.png" %}" type="image/png">
    <link rel="apple-touch-icon" href="{% static "base/img/apple-touch-icon.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "base/img/apple-touch-icon-72x72.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "base/img/apple-touch-icon-114x114.png" %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/bootstrap.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/prettyPhoto.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "/base/css/style.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "base/fonts/font-awesome/css/font-awesome.css" %}">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
    <!-- js -->
    <script type="text/javascript" src="{% static "/base/js/modernizr.custom.js" %"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
    <script type="text/javascript" src="{% static "/base/js/jquery.1.11.1.js" %}"></script> 
    <script>
      $(window).load(function() {
        setTimeout(()=>{
          $(".se-pre-con").fadeOut('medium');
        },300);
      });</script>
</head>
<body>
    
<!-- Navigation  ==========================================-->
<nav id="menu" class="navbar navbar-default navbar-fixed-top on">
        <div class="container"> 
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="{% url 'index' %}">
              <strong><img src="{% static "base/img/ace.png" %}" width="40" alt=""> Ace Foundation Academy</strong></a> </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/#home" class="page-scroll">Home</a></li>
              <li><a href="/#services-section" class="page-scroll">Courses</a></li>
              <li><a href="/#gallery" class="page-scroll">Gallery</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'notes' %}" class="page-scroll">Notes</a></li>
              {% endif %}
              <li><a href="/#about-section" class="page-scroll">About</a></li>
              <li><a href="/#team-section" class="page-scroll">Teachers</a></li>
              <li><a href="/#contact-section" class="page-scroll">Contact</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'users:logout' %}" class="page-scroll authen">Logout</a></li>
              <li><a href="{% url 'users:profile' %}" class="page-scroll authen">Profile</a></li>
              {% else %}
              <li><a href="{% url 'users:login' %}" class="page-scroll authen">Login</a></li>
              <li><a href="{% url 'users:register' %}" class="page-scroll authen">Register</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>xn/.

    <!-- All the other stuffs goes in here -->

    {% block content %}

    {% endblock %}


    <!-- Rest of the thing goes on -->
    <div id="social-section">
        <div class="container">
          <div class="social">
            <ul>
              <li><a href="https://www.facebook.com/ACEFoundationAcademy/"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    <!-- Footer Part Begins -->
    <div id="footer">
        <div class="container">
          <div class="fnav">
            <p>Copyright &copy; ACE FOUNDATION ACADEMY. Designed <a href="http://www.github.com/xritzx" rel="nofollow">by</a></p>
          </div>
        </div>
    </div>

<!-- All of the needed javascript Files -->
<script type="text/javascript" src="{% static "base/js/bootstrap.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/SmoothScroll.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.counterup.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/waypoints.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.prettyPhoto.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jquery.isotope.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/jqBootstrapValidation.js" %}"></script> 
<script type="text/javascript" src="{% static "base/js/main.js" %}"></script>

</body>
<style>
  .no-js #loader { display: none;  }
.js #loader { display: block; position: absolute; left: 100px; top: 0; }
.se-pre-con {
	position: fixed;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	z-index: 9999;
	background: url("{% static "/loader/loader.svg" %}") center no-repeat #fff;
}
</style>
<div class="se-pre-con"></div>

</html>