Ace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^auth/', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from .views import register, user_login, user_logout, user_info

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^profile/$', user_info, name='profile')
]

users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator, MaxLengthValidator
from base.models import departments
from multiselectfield import MultiSelectField

MAX_VAL = 10**16
MIN_VAL = 10**9
YEAR = []

def fetch_year():
    YEAR.clear()
    yr = datetime.now().year
    for r in range(yr-5, yr+5):
        YEAR.append((str(r),str(r)))
fetch_year()

#Model Class for more feature
class UserProfile(models.Model):

    user = models.OneToOneField(User)

    contact_number = models.IntegerField(validators=[MinValueValidator(MIN_VAL), MaxValueValidator(MAX_VAL)], blank=True, help_text="Optional Example: XXXXXXXXXX")
    guardian_name = models.CharField(max_length=40, help_text="Father/Mother/Gaurdian Name")
    contact_number_of_guardian = models.IntegerField(validators=[MinValueValidator(MIN_VAL), MaxValueValidator(MAX_VAL)], help_text="Required * Example: XXXXXXXXXX")
    address = models.TextField(blank=True, help_text="Optional")
    subjects = MultiSelectField(choices=departments, default=departments[0][0])

    class_X_school_name = models.CharField(max_length=40, help_text="Enter your School Name", blank=True)
    class_X_board_name = models.CharField(max_length=6, choices=(("CBSE", "CBSE"), ("ICSE", "ICSE"), ("WBSE", "WBSE")), default="ICSE")
    class_X_year_of_passing = models.CharField(choices=YEAR, max_length=5)
    last_exam_marksheet = models.ImageField(upload_to="users/marksheet", blank=True, help_text="Marksheet should name as 'YOUR_NAME_CLASS' less than 200kB")

    profile_pic = models.ImageField(upload_to="users/profile_pic", blank=True, help_text="Image should be less than 200kB")

    def getClass(self):
        if(datetime.now().month<=3):
            return (10-(int(self.class_X_year_of_passing) - datetime.now().year))
        else:
            return (11-(int(self.class_X_year_of_passing) - datetime.now().year))

    def __str__(self):
        return self.user.first_name + " Username: " + self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Minimum 8 characters, Must include special characters and numbers.")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user',)
 

users/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect, HttpResponse
from .models import User, UserProfile

def register(req):
    registered = False
    entered = False
    if(req.method == "POST"):
        
        entered = True
        user_form = UserForm(data=req.POST)
        profile_form = UserProfileForm(data=req.POST)

        if(user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save() #Saving the Instant User Values

            profile = profile_form.save(commit=False)
            profile.user = user #Fetching Value into one to on field

            # uploading raw image of marksheets and profile
            if 'profile_pic' in req.FILES:
                profile.profile_pic = req.FILES['profile_pic']

            profile.save()
            entered = False
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)
        
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(req, 'users/register.html', {'registered':registered,
                                                'entered':entered,
                                                 'user_form':user_form,
                                                    'profile_form':profile_form})

def user_login(req):
    if(req.method == "POST"):
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if(user.is_active):
                login(req, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not activated yet or is deactivated")
        else:
            return render(req, 'users/login.html', {'failed': True})
    else:
        return render(req, 'users/login.html', {'failed': False})

@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_info(req):
    user_data = req.user
    return render(req, 'users/user_info.html', {
        'user_data':user_data
        })

templates/users/login.html
{% extends "base/structure_nav.html" %}

{% block title %}
    Login
{% endblock %}


{% block content %}
{% load staticfiles %}

  <div id="contact-section" class="text-center">
  <div class="container">
    {% if failed %}
    <h2 style="color:rgba(255, 118, 118, 0.89)">Login failed, Please enter the Username and Password correctly</h2>
    {% else %}
    <kbd style="font-size:50px;">Login</kbd>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      <div class="row">

        <div class="col-md-12">
          <div class="form-group signupin">
              <label for="username" class="lead">Username: </label>
              <input type="text" name="username" class="form-control" placeholder="Enter Your Username">
              <p class="help-block text-danger"></p>
          </div>
        </div> 

        <div class="col-md-12">
          <div class="form-group signupin">
            <label for="password" class="lead">Password: </label>
            <input type="password" name="password" class="form-control" placeholder="Enter Your Password">
            <p class="help-block text-danger"></p>
          </div>
        </div>
      </div>
      <input type="submit" class="btn btn-default" value="Login">

      </form>
  </div>
  </div>

{% endblock %}

templates/users/register.html
{% extends "base/structure_nav.html" %}
{% block title %}
    Registration
{% endblock %}


{% block content %}
{% load staticfiles %}
{% load widget_tweaks %}

<div id="contact-section" class="text-center">

<div class="container">
 
    {% if registered %}
        <h1>Congrats You are registered, get your account activated by visiting us at our center</h1>

    {% else %}
        {% if entered %}
            <h1> <span style="color:rgb(255, 95, 95)">Registration Failed</span>, Please enter the details carefully</h1>
        {% else %}
            <kbd style="font-size:50px;">Register</kbd>
        {% endif %}
        
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {% for field in user_form %}
            <div class="form-group signupin">
                    {{ field.label_tag }}
                    <span style="color:red">{{ field.errors }}</span>
                    {% render_field field class="form-control" %}
                    {{ field.help_text }}
            </div>
            {% endfor %}
            {% for field in profile_form %}
            <div class="form-group signupin">
                    {{ field.label_tag }}
                    {{ field.errors }}
                    {% render_field field class="form-control" %}
                    {{ field.help_text }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Register</button>        
        </form>

    {% endif %}
</div>
</div>

<script>
    var no = $('#id_contact_number');
    no.on('click',()=>{
        if(no.attr('value')<1000000000){
            alert("Enter a Valid Phone no.");
        }
    });
    
</script>
{% endblock %}

templates/users/user_info.html
{% extends "base/structure_nav.html" %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
{% load staticfiles %}

<div id="contact-section" class="text-center">
    <div class="container">
    <div class="thumbnail">
    {% if user_data.userprofile.profile_pic %}
    <a href="{{user_data.userprofile.profile_pic}}" rel="prettyPhoto"><img src="{{user_data.userprofile.profile_pic}}" alt="Photo" class="img-circle team-img"></a>
    {% endif %}
        <div class="caption">
            <h3><strong>Username: <br></strong>{{ user_data.username }}</h3>
            <h4><strong>Name: <br></strong>{{ user_data.first_name }} {{ user_data.last_name }}</h4><br>
            <h4><strong>Class: <br></strong>{{ user_data.userprofile.getClass }}</h4><br>

            <h4><strong>Guardian Name: <br></strong>{{ user_data.userprofile.guardian_name }}</h4><br>
            <h4><strong>Guardian Contact: <br></strong>{{ user_data.userprofile.contact_number_of_guardian }}</h4><br>
            <h4><strong>Address: </strong><address>{{ user_data.userprofile.address }}</address></h4><br>

            <h4><strong>Class X School Name: <br></strong>{{ user_data.userprofile.class_X_school_name }}({{ user_data.userprofile.class_X_board_name }})</h4>
            
            <h4><strong>Subject Opted in ACE for </strong>({{ user_data.userprofile.class_X_board_name }}): <br>{{ user_data.userprofile.subjects }}</h4>
        </div>
    </div>
</div>
</div>
{% endblock %}